"""
models/intelligence/peer_comparator.py — Cohort-based peer spending comparison.

Finds the user's financial archetype (nearest k-means cluster in VAE embedding space)
and computes their per-category spending percentile within that peer group.

Requires
--------
  models/saved/user_archetypes.pt      — k-means centers + archetype names
  models/saved/cohort_spend_stats.pt   — per-cluster, per-category spend distributions
Both are generated by training/train_user_vae.py.
"""

from __future__ import annotations

import torch
import numpy as np

CATEGORIES = [
    "dining", "groceries", "subscriptions", "transportation",
    "utilities", "entertainment", "shopping", "healthcare", "other",
]

_ARCHETYPE_DESCRIPTIONS: dict[str, str] = {
    "Balanced Saver":           "well-balanced spender who saves consistently",
    "Dining-Heavy":             "frequent diner who enjoys eating out",
    "Subscription Heavy":       "subscription-heavy user with many recurring services",
    "Transport Commuter":       "heavy commuter with significant transportation costs",
    "Healthcare Focused":       "health-conscious spender prioritizing medical care",
    "Entertainment Enthusiast": "entertainment-first spender who loves experiences",
    "Grocery Optimizer":        "grocery-smart shopper who cooks at home",
    "Impulse Spender":          "spontaneous spender with irregular patterns",
}


class PeerComparator:
    """
    Compares a user's spending to their financial peer group.

    Parameters
    ----------
    archetype_data : dict loaded from user_archetypes.pt
        Keys: centers (k, 64), labels (N,), names (list[str]), k (int)
    cohort_stats   : dict loaded from cohort_spend_stats.pt
        Format: {cluster_idx: {category: {mean, median, p25, p75}}}
    """

    def __init__(self, archetype_data: dict, cohort_stats: dict) -> None:
        self.archetype_data = archetype_data
        self.cohort_stats   = cohort_stats
        self.centers: torch.Tensor = archetype_data["centers"].cpu().float()
        self.names:   list[str]    = archetype_data["names"]

    def compare(
        self,
        user_embedding:     torch.Tensor,       # (1, 64) or (64,)
        user_monthly_spend: dict[str, float],   # {category: $ spent/month}
    ) -> dict:
        """
        Assign the user to an archetype and compute spending percentiles.

        Returns
        -------
        dict with keys:
          archetype         : str
          archetype_idx     : int
          archetype_description : str
          cohort_medians    : {category: float}
          your_monthly      : {category: float}
          percentiles       : {category: int}  0–100
          top_differences   : list[{category, your_spend, cohort_median, percentile, ratio}]
          message           : str
        """
        emb   = user_embedding.squeeze().unsqueeze(0).cpu().float()  # (1, 64)
        dists = torch.cdist(emb, self.centers)                        # (1, k)
        idx   = int(dists.argmin().item())
        name  = self.names[idx] if idx < len(self.names) else f"Archetype {idx}"
        desc  = _ARCHETYPE_DESCRIPTIONS.get(name, "unique spender")

        stats = self.cohort_stats.get(idx, {})

        cohort_medians: dict[str, float] = {}
        percentiles:    dict[str, int]   = {}

        for cat in CATEGORIES:
            s      = stats.get(cat, {})
            median = float(s.get("median", 0.0))
            p25    = float(s.get("p25", 0.0))
            p75    = float(s.get("p75", 0.0))
            cohort_medians[cat] = round(median, 2)

            u = float(user_monthly_spend.get(cat, 0.0))
            percentiles[cat] = _estimate_percentile(u, p25, median, p75)

        diffs = [
            {
                "category":      cat,
                "your_spend":    round(user_monthly_spend.get(cat, 0.0), 2),
                "cohort_median": cohort_medians[cat],
                "percentile":    percentiles[cat],
                "ratio":         round(
                    user_monthly_spend.get(cat, 0.0) / max(cohort_medians[cat], 1.0), 2
                ),
            }
            for cat in CATEGORIES
            if cohort_medians[cat] > 0 or user_monthly_spend.get(cat, 0.0) > 0
        ]
        diffs.sort(key=lambda d: d["percentile"], reverse=True)

        message = _build_message(name, desc, diffs)

        return {
            "archetype":             name,
            "archetype_idx":         idx,
            "archetype_description": desc,
            "cohort_medians":        cohort_medians,
            "your_monthly":          {k: round(float(v), 2) for k, v in user_monthly_spend.items()},
            "percentiles":           percentiles,
            "top_differences":       diffs[:4],
            "message":               message,
        }


# ── Helpers ───────────────────────────────────────────────────────────────────

def _estimate_percentile(value: float, p25: float, median: float, p75: float) -> int:
    """Linear interpolation across known quantile breakpoints → 0–100 percentile."""
    if p75 <= p25:
        return 50
    if value <= 0 and p25 <= 0:
        return 0
    if value <= p25:
        base = max(p25, 1e-6)
        return max(0, int(25 * value / base))
    if value <= median:
        span = max(median - p25, 1e-6)
        return int(25 + 25 * (value - p25) / span)
    if value <= p75:
        span = max(p75 - median, 1e-6)
        return int(50 + 25 * (value - median) / span)
    span = max(p75, 1e-6)
    return min(99, int(75 + 25 * (value - p75) / span))


def _build_message(name: str, desc: str, diffs: list[dict]) -> str:
    if not diffs:
        return f"You're a {name} — a {desc}."
    top = diffs[0]
    pct = top["percentile"]
    rank_str = f"top {100 - pct}%" if pct >= 50 else f"bottom {pct}%"
    return (
        f"You're a {name} — a {desc}. "
        f"Your highest relative category is {top['category']}: "
        f"${top['your_spend']:.0f}/month vs the peer median of ${top['cohort_median']:.0f} "
        f"({rank_str} of similar users)."
    )
